queries:
  - exclude: cpp/missing-return
  - exclude: cpp/use-of-goto
  - include: cpp/bad-addition-overflow-check
  - include: cpp/overflow-calculated
  - include: cpp/compare-where-assign-meant
  - include: cpp/assign-where-compare-meant
  - include: cpp/conditionally-uninitialized-variable
  - include: cpp/tainted-format-string
  - include: cpp/memory-never-freed
  - include: cpp/memory-may-not-be-freed
  - include: cpp/new-free-mismatch
  - include: cpp/pointer-overflow-check
  - include: cpp/bad-strncpy-size
  - include: cpp/improper-null-termination
  - include: cpp/integer-overflow-tainted
  - include: cpp/overflowing-snprintf
  - include: cpp/overrunning-write
  - include: cpp/uninitialized-local
  - include: cpp/unsafe-strncat
  - include: cpp/unsafe-strcat
  - include: cpp/use-after-free
  - include: cpp/signed-overflow-check
  - include: cpp/static-buffer-overflow
  - include: cpp/unbounded-write
  - include: cpp/dangerous-function-overflow
